baseURL = "https://sosomasox.com/"
languageCode = "ja"
title = "sosomasox"
theme = "anatole"
hasCJKLanguage = true
DefaultContentLanguage = "ja"

[params]
title = "sosomasox"
author = "sosomasox"
profilePicture = "images/profile.jpg"
thumbnail = "images/profile.jpg"
twitter = "sosomasox"
commpost = true

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/sosomasox"

    [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/sosomasox"
    
    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:t-soma@sosomasox.com"

[menue]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 200
    url = "/posts/"

    [[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 300
    url = "/portfolio/"

    [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 400
    url = "/about/"

    [[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 500
    url = "/contact/"

    [[menu.footer]]
    name = "imprint"
    identifier = "imprint"
    weight = 1
    url = "/imprint/"
